-- 003: Campos extendidos de propriedade
ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS street            text,
  ADD COLUMN IF NOT EXISTS number            text,
  ADD COLUMN IF NOT EXISTS block             text,
  ADD COLUMN IF NOT EXISTS floor_letter      text,
  ADD COLUMN IF NOT EXISTS fracao            text,
  ADD COLUMN IF NOT EXISTS property_subtype  text,
  ADD COLUMN IF NOT EXISTS use_type          text,
  ADD COLUMN IF NOT EXISTS use_subtype       text,
  ADD COLUMN IF NOT EXISTS id_registo_predial    text,
  ADD COLUMN IF NOT EXISTS id_registo_matricial  text,
  ADD COLUMN IF NOT EXISTS tipo_predio       text,
  ADD COLUMN IF NOT EXISTS destino           text,
  ADD COLUMN IF NOT EXISTS composicao_imovel text,
  ADD COLUMN IF NOT EXISTS area_garage_m2    numeric,
  ADD COLUMN IF NOT EXISTS area_annex_m2     numeric,
  ADD COLUMN IF NOT EXISTS useful_area       numeric,
  ADD COLUMN IF NOT EXISTS land_area         numeric,
  ADD COLUMN IF NOT EXISTS year_built        integer,
  ADD COLUMN IF NOT EXISTS visit_date        date,
  ADD COLUMN IF NOT EXISTS po_number         text,
  ADD COLUMN IF NOT EXISTS po_date           date,
  ADD COLUMN IF NOT EXISTS invoice_number    text,
  ADD COLUMN IF NOT EXISTS invoice_date      date,
  ADD COLUMN IF NOT EXISTS payment_date      date;
