-- 007: Tabela abanca_datatape com campos em português
CREATE TABLE IF NOT EXISTS abanca_datatape (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  portfolio_id              uuid REFERENCES portfolios(id) ON DELETE CASCADE,
  property_id               uuid REFERENCES properties(id) ON DELETE SET NULL,
  -- Campos originais do ficheiro ABANCA (91 campos)
  id_bien                   text,
  nuc_risco                 text,
  tipo_bien                 text,
  subtipo_bien              text,
  situacion                 text,
  direccion                 text,
  numero                    text,
  bloque                    text,
  escalera                  text,
  piso                      text,
  puerta                    text,
  codigo_postal             text,
  nombre_municipio          text,
  nombre_provincia          text,
  nombre_distrito           text,
  nombre_concelho           text,
  superficie_adoptada_finca numeric,
  superficie_adoptada_elem  numeric,
  ano_construccion          integer,
  estado_conservacion       text,
  uso                       text,
  destino                   text,
  referencia_catastral      text,
  referencia_registral      text,
  numero_finca              text,
  tipo_operacion            text,
  finalidad                 text,
  tipo_tasacion             text,
  fecha_solicitud           date,
  fecha_visita              date,
  fecha_entrega             date,
  valor_tasacion            numeric,
  valor_hipoteca            numeric,
  raw_data                  jsonb,
  created_at                timestamptz DEFAULT now()
);
