-- 015: Campos novos para tabs actualizadas

ALTER TABLE properties
  -- Tab 3
  ADD COLUMN IF NOT EXISTS nr_conservatoria      text,
  ADD COLUMN IF NOT EXISTS nome_conservatoria    text,
  ADD COLUMN IF NOT EXISTS nome_proprietario     text,
  ADD COLUMN IF NOT EXISTS tipo_caderneta        text,
  ADD COLUMN IF NOT EXISTS seccao_caderneta      text,
  ADD COLUMN IF NOT EXISTS ano_matriz            integer,
  ADD COLUMN IF NOT EXISTS cod_freg              text,
  ADD COLUMN IF NOT EXISTS freguesia_financas    text,
  -- Tab 5
  ADD COLUMN IF NOT EXISTS nome_pq               text,
  ADD COLUMN IF NOT EXISTS nr_pq                 text,
  ADD COLUMN IF NOT EXISTS nr_licenca_utilizacao text,
  ADD COLUMN IF NOT EXISTS obra_parada           text,
  -- Tab 7 — Rendas
  ADD COLUMN IF NOT EXISTS renda_ef_descricao    text,
  ADD COLUMN IF NOT EXISTS renda_ef_area         numeric,
  ADD COLUMN IF NOT EXISTS renda_ef_valor_m2     numeric,
  ADD COLUMN IF NOT EXISTS renda_ef_mensal       numeric,
  ADD COLUMN IF NOT EXISTS renda_ef_taxa         numeric,
  ADD COLUMN IF NOT EXISTS renda_ef_total        numeric,
  ADD COLUMN IF NOT EXISTS renda_pot_descricao   text,
  ADD COLUMN IF NOT EXISTS renda_pot_area        numeric,
  ADD COLUMN IF NOT EXISTS renda_pot_valor_m2    numeric,
  ADD COLUMN IF NOT EXISTS renda_pot_mensal      numeric,
  ADD COLUMN IF NOT EXISTS renda_pot_taxa        numeric,
  ADD COLUMN IF NOT EXISTS renda_pot_total       numeric,
  -- Tab 7 — Custo
  ADD COLUMN IF NOT EXISTS custo_terreno_m2          numeric,
  ADD COLUMN IF NOT EXISTS custo_construcao_m2       numeric,
  ADD COLUMN IF NOT EXISTS custos_indiretos_pct      numeric,
  ADD COLUMN IF NOT EXISTS margem_promotor_pct       numeric,
  ADD COLUMN IF NOT EXISTS depreciacao_pct           numeric,
  ADD COLUMN IF NOT EXISTS custo_area                numeric,
  ADD COLUMN IF NOT EXISTS custo_terreno_total       numeric,
  ADD COLUMN IF NOT EXISTS custo_construcao_total    numeric,
  ADD COLUMN IF NOT EXISTS custo_repos_bruto         numeric,
  ADD COLUMN IF NOT EXISTS depreciacao_valor         numeric,
  ADD COLUMN IF NOT EXISTS custo_repos_liquido       numeric,
  ADD COLUMN IF NOT EXISTS valor_seguro_cc_ci        numeric,
  ADD COLUMN IF NOT EXISTS hec_custo_terreno_m2      numeric,
  ADD COLUMN IF NOT EXISTS hec_custo_construcao_m2   numeric,
  ADD COLUMN IF NOT EXISTS hec_custos_indiretos_pct  numeric,
  ADD COLUMN IF NOT EXISTS hec_margem_promotor_pct   numeric,
  ADD COLUMN IF NOT EXISTS hec_custo_repos_bruto     numeric,
  ADD COLUMN IF NOT EXISTS hec_valor_seguro          numeric,
  ADD COLUMN IF NOT EXISTS hec_custo_repos_actual    numeric,
  ADD COLUMN IF NOT EXISTS hec_invest_pendente       numeric,
  ADD COLUMN IF NOT EXISTS justificacao_depreciacao  text,
  -- Tab 9
  ADD COLUMN IF NOT EXISTS cond_observacoes          text,
  -- Tab 11
  ADD COLUMN IF NOT EXISTS valor_seguro_atual        numeric,
  ADD COLUMN IF NOT EXISTS pct_obra_atual            numeric,
  -- Obras de Beneficiação
  ADD COLUMN IF NOT EXISTS obras_orcamento_apres     numeric,
  ADD COLUMN IF NOT EXISTS obras_orcamento_est       numeric,
  ADD COLUMN IF NOT EXISTS obras_valorizacao         numeric,
  ADD COLUMN IF NOT EXISTS obras_licenca_camara      text,
  ADD COLUMN IF NOT EXISTS obras_valor_antes         numeric,
  ADD COLUMN IF NOT EXISTS obras_valor_apos          numeric,
  ADD COLUMN IF NOT EXISTS obras_pct_realizada       numeric,
  ADD COLUMN IF NOT EXISTS obras_valor_atual         numeric,
  ADD COLUMN IF NOT EXISTS obras_descricao           text,
  -- Método Residual
  ADD COLUMN IF NOT EXISTS resid_est_descricao       text,
  ADD COLUMN IF NOT EXISTS resid_est_area            numeric,
  ADD COLUMN IF NOT EXISTS resid_est_valor_m2        numeric,
  ADD COLUMN IF NOT EXISTS resid_est_total           numeric,
  ADD COLUMN IF NOT EXISTS resid_est_obs             text,
  ADD COLUMN IF NOT EXISTS resid_din_descricao       text,
  ADD COLUMN IF NOT EXISTS resid_din_area            numeric,
  ADD COLUMN IF NOT EXISTS resid_din_valor_m2        numeric,
  ADD COLUMN IF NOT EXISTS resid_din_total           numeric,
  ADD COLUMN IF NOT EXISTS resid_din_obs             text;

-- Certificação — campos novos
ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS empresa_nome           text,
  ADD COLUMN IF NOT EXISTS empresa_nif            text,
  ADD COLUMN IF NOT EXISTS empresa_cmvm           text,
  ADD COLUMN IF NOT EXISTS empresa_apolice        text,
  ADD COLUMN IF NOT EXISTS empresa_data_validade  date,
  ADD COLUMN IF NOT EXISTS empresa_seguradora     text,
  ADD COLUMN IF NOT EXISTS empresa_assinatura     text,
  ADD COLUMN IF NOT EXISTS pac_nome               text,
  ADD COLUMN IF NOT EXISTS pac_ordem              text,
  ADD COLUMN IF NOT EXISTS pac_cmvm               text,
  ADD COLUMN IF NOT EXISTS pac_apolice            text,
  ADD COLUMN IF NOT EXISTS pac_data_validade      date,
  ADD COLUMN IF NOT EXISTS pac_seguradora         text,
  ADD COLUMN IF NOT EXISTS pac_assinatura         text,
  ADD COLUMN IF NOT EXISTS perito_ordem           text,
  ADD COLUMN IF NOT EXISTS perito_assinatura      text;
